### ISSUE TITLE
为什么这套打印模版整合其他的项目整合不了

### ISSUE THREAD

**Issue by jsonQin** [myliuxia/kr-print-designer#1]
单独运行demo是没问题的可以操作，但是整合自己的demo或者整合其他项目都有问题，没有显示任何东西，[Vue warn]: Failed to mount component: template or render function not defined
 这个错误

**Comment by myliuxia** [comment]
你项目是用vue-cli搭建的吗？这个按照文档流程按照、引入组件是没有问题的

**Comment by jsonQin** [comment]
是vue-cli搭建的啊 ，不行啊，单独跑demo没问题，引入项目就不行，能否加联系方式 细聊一下 690769740，谢谢大神
















在 2020-11-24 17:20:31，"LiuXia" <notifications@github.com> 写道：

你项目是用vue-cli搭建的吗？这个按照文档流程按照、引入组件是没有问题的

**Comment by jsonQin** [comment]
qq：690769740，麻烦大神了



在 2020-11-24 17:20:31，"LiuXia" <notifications@github.com> 写道：

你项目是用vue-cli搭建的吗？这个按照文档流程按照、引入组件是没有问题的
