### ISSUE TITLE
组件渲染引入后渲染数据问题

### ISSUE THREAD

**Issue by stevexiongzy** [myliuxia/kr-print-designer#2]
引入组件后，在预览数据时出现问题，项目example没问题，npm引入出现问题，项目使用vue-cli搭建。
![image](https://user-images.githubusercontent.com/55369176/100330246-b1289d80-3009-11eb-9584-052942ba7c88.png)
![image](https://user-images.githubusercontent.com/55369176/100330394-dd441e80-3009-11eb-8b71-83912a052553.png)
![image](https://user-images.githubusercontent.com/55369176/100330354-d3222000-3009-11eb-9a79-a5447b7c758a.png)
，是什么兼容方面的问题嘛

**Comment by myliuxia** [comment]
这个问题是旧版本的bug，请使用1.0.6版本
