### ISSUE TITLE
demo没问题，但是集成到自己的项目中设计页面有点问题

### ISSUE THREAD

**Issue by Chen491733492** [myliuxia/kr-print-designer#4]
打开设计页面后，页面会卡主，点添加组件或者任意的操作，页面没有变化。但是返回的data数据其实是变化了。  如果tempItems里面有组件的话，会出现 自定义元素报错的现象。
![image](https://user-images.githubusercontent.com/38376093/109125712-59740c80-7787-11eb-92b5-58eae5e53616.png)
还有一个小问题，在这个方法里面  应该去判断data的长度大于0而不是1吧。
![image](https://user-images.githubusercontent.com/38376093/109126064-cc7d8300-7787-11eb-8490-d495f883ca00.png)

**Comment by X-kuro** [comment]
> 打开设计页面后，页面会卡主，点添加组件或者任意的操作，页面没有变化。但是返回的data数据其实是变化了。 如果tempItems里面有组件的话，会出现 自定义元素报错的现象。 ![image](https://user-images.githubusercontent.com/38376093/109125712-59740c80-7787-11eb-92b5-58eae5e53616.png) 还有一个小问题，在这个方法里面 应该去判断data的长度大于0而不是1吧。 ![image](https://user-images.githubusercontent.com/38376093/109126064-cc7d8300-7787-11eb-8490-d495f883ca00.png)

我也遇到这个问题了，请问你找到解决方法吗

**Comment by yangweiran101** [comment]
> 打开设计页面后，页面会卡主，点添加组件或者任意的操作，页面没有变化。但是返回的data数据其实是变化了。 如果tempItems里面有组件的话，会出现 自定义元素报错的现象。 ![image](https://user-images.githubusercontent.com/38376093/109125712-59740c80-7787-11eb-92b5-58eae5e53616.png) 还有一个小问题，在这个方法里面 应该去判断data的长度大于0而不是1吧。 ![image](https://user-images.githubusercontent.com/38376093/109126064-cc7d8300-7787-11eb-8490-d495f883ca00.png)

我也是这个问题，我也不知道咋回事，保存的时候数据已经在tempLates里面了，但是没有同步回显在模板上。

**Comment by myliuxia** [comment]
该问题已在1.1.7版本解决，问题原因据我分析应该是package.json应用的vue放在dependencies中的，导致如果项目vue的版本与组件版本时出现上述问题
