### ISSUE TITLE
可以直接通过按钮打印吗？不唤醒预览页面。

### ISSUE THREAD

**Issue by fangmuke** [myliuxia/kr-print-designer#5]

**Comment by myliuxia** [comment]
是可以直接打印的，按照文档调用print()方法就行了。
![image](https://user-images.githubusercontent.com/30226066/117385273-5760c380-af17-11eb-8034-20201b0af5ed.png)
示例里的直接打印调用错了方法，之后会更新。
欢迎反馈问题，欢迎star
