### ISSUE TITLE
可以加多几个组件吗，比如table，条形码和二维码等

### ISSUE THREAD

**Issue by huanglsj** [myliuxia/kr-print-designer#6]
可以加多几个组件吗，比如table，条形码和二维码等

**Comment by myliuxia** [comment]
![image](https://user-images.githubusercontent.com/30226066/120283434-c5699200-c2ed-11eb-936b-8ccb77154f10.png)
目前打印项已包含文本、表格、html、图片、条码。二维码可通过图片或html片段实现
