### ISSUE TITLE
table能否控制行或列

### ISSUE THREAD

**Issue by Lee66** [myliuxia/kr-print-designer#8]
像下图这样，如果需要多行不知道行不行，多行的目的是为了占位和后期替换数据，不占位的话无法知道可以放几行。还有一些建议：表格行或列拖拽变窄变宽、删减行列等
<div yne-bulb-block="paragraph" style="white-space: pre-wrap; text-align: left; line-height: 1.75; font-size: 14px;"><br></div><div yne-bulb-block="table" style="overflow: auto;">

项目名称 | [单价] | [数量] | [金额]
-- | -- | -- | --
项目名称0 | 单价0 | 数量0 | 金额0
项目名称1 | 单价1 | 数量1 | 金额1
项目名称2 | 单价2 | 数量2 | 金额2
项目名称3 | 单价3 | 数量3 | 金额3

</div><div yne-bulb-block="paragraph" style="white-space: pre-wrap; text-align: left; line-height: 1.75; font-size: 14px;"><br></div>

**Comment by xixilalaha** [comment]
请问行列的宽度你这边能做到了么

**Comment by myliuxia** [comment]
表格目前还不支持这些功能，如果需要自定义样式可以使用 模板类型为braid-html的打印项
